### ISSUE TITLE
RSSI graph: tapping an icon doesn't always dim all other graphs - 2.4.13 (86) - defect

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Connect#100]
Choose RSSI graph. Swipe down to clear and start scan
Wait 10 seconds and see many graphs.Stop scan.
Tap a single icon 
Expected: the graph for that device highlighted, i.e. all other devices se to gray
Actual : all other icons set to try but all graphs remain colored.

![image](https://user-images.githubusercontent.com/2365961/134504476-0ecb146c-4ab6-4f67-9330-576326de7c50.png)

**Comment by dinesharjani** [comment]
I think this has been fixed for 2.7.7. Please reissue / reopen if after the update is released, you still see it.
