### ISSUE TITLE
on Filtering toggle a switch leads to clearing the parameters value

### ISSUE THREAD

**Issue by ivnny** [NordicSemiconductor/IOS-nRF-Connect#106]
type some data to be filtered and toggle a switch related to this field and it will clear the user input

**Comment by dinesharjani** [comment]
This is a good one. Thanks for reporting.

**Comment by dinesharjani** [comment]
Ok, this is fixed now @ivnny. Ping me if you'd like to test it on TestFlight for the upcoming version 2.5. Thanks.

**Comment by ivnny** [comment]
@dinesharjani yes pls add me as a tester, I'm working a lot with your app and would like to contribute

**Comment by dinesharjani** [comment]
@ivnny I need your email address to add you. You can reach me by using the in-app 'Send Feedback' feature.
