### ISSUE TITLE
RSSI bar invalid for values below -35dBm

### ISSUE THREAD

**Issue by Klievan** [NordicSemiconductor/IOS-nRF-Connect#112]
For values below -35dBm (-34 to -6 observed) the signal bar turns red as shown in the screenshots below:
![image](https://user-images.githubusercontent.com/5279685/176187289-47cc21b1-d07e-4d2a-81e0-81a86567cc6a.png)
![image](https://user-images.githubusercontent.com/5279685/176187341-abe6d17d-2db2-4b33-a1b9-db3984ef8662.png)

**Comment by dinesharjani** [comment]
Yeah, so, in the code the practical 'best' was determined to be around -36dB, hence the switch to 'bad signal' color.

We've made the change and it'll ship as part of 2.5.2 very soon.
