### ISSUE TITLE
Hex string 

### ISSUE THREAD

**Issue by ShirishKhasnis** [NordicSemiconductor/IOS-nRF-Connect#117]
Dear member 

I can’t receive full hex string on nRF connect 
It will terminate after 0x00 
Please help me to solve this problems

**Comment by philips77** [comment]
Hello,
Please attach a screenshot, describe the issue, show what data are sent by the device, say what would be the expected result.

**Comment by dinesharjani** [comment]
@ShirishKhasnis hi, can you provide us with a screenshot / some way to reproduce the issue?
