### ISSUE TITLE
DFU with NCS MCUBoot fails sometimes

### ISSUE THREAD

**Issue by trueb2** [NordicSemiconductor/IOS-nRF-Connect#118]
I have experienced for several versions of both the NRF Connect iOS app and NRF Connect SDK an issue where NRF Connect iOS cannot OTA DFU with MCUBoot. I am opening an issue here because it does not seem to be an issue with the NRF Connect SDK. The NRF Toolbox iOS app succeeds to performing the OTA DFU update procedure. Both apps will sometimes timeout during sending the binary and succeed after retry when that happens. Specifically, the issue at hand is that NRF Connect iOS may not be able to initiate OTA DFU for the same sensor that NRF Toolbox iOS can.

One screenshot shows a failure on NRF Connect iOS that eventually results in a timeout (even after reattempt). The other screenshot shows the beginning of the logs from a NRF Toolbox success.

![IMG_4925](https://user-images.githubusercontent.com/8592049/197590654-3ac355f5-49cb-49a0-8b38-5b47dae90e82.PNG)
![IMG_4924](https://user-images.githubusercontent.com/8592049/197590658-d15b6384-5e80-47cf-8b24-69760a48dc9d.PNG)

**Comment by dinesharjani** [comment]
Hi @trueb2 - the version of nRF Connect on the App Store has an 'old' internal version of the DFU Library for OTA Updates. We're working as fast as we can on the new version, 2.6, but it's pretty big. What we can do in the meantime is I can add you to the TestFlight beta builds of it so you can check it out and let us know if the issue persists.

**Comment by trueb2** [comment]
@dinesharjani That would be great!

**Comment by dinesharjani** [comment]
@trueb2 Write me at dinesh.harjani@nordicsemi.no with the email to add to our TestFlight Group. That's all :)
