### ISSUE TITLE
How to specify custom advertising service?

### ISSUE THREAD

**Issue by akohlsmith** [NordicSemiconductor/IOS-nRF-Connect#121]
I can specify custom uuids for server services, but I cannot do so for the advertising part of the virtual peripheral. V2.5.3 build 4 on iOS.

**Comment by rego21** [comment]
Hey,

Im also trying to do it. You can add a custom server with a service's uuid of 128 bits, however you cannot add an advertiser with a custom uuid only the pre defined ones.

thanks!

**Comment by dinesharjani** [comment]
You know the app better than I do :)

Marking as closed.

**Comment by rego21** [comment]
Im curious if the same happens in Android, sadly I don't have one to test :(

**Comment by philips77** [comment]
Hi, on Android it's possible to set UUIDs for services and in Advertising. As the API is more flexible, you should also be able to set the Service Data, Manufacturer data and some other advertising parameters.
