### ISSUE TITLE
nRF connect not showing DFU files after airdropping from MacBook

### ISSUE THREAD

**Issue by hussainaloum** [NordicSemiconductor/IOS-nRF-Connect#125]
Hello

I have a MacBook with some DFU files that I used to airdrop DFU files to my iOS device. Now After I airdrop the DFU files I have to kill the nRF connect app for the files to show up so I can DFU

can you fix that? It’s making the app annoying to use

**Comment by dinesharjani** [comment]
Hi,

I just made a fix for this on the TestFlight Beta. If you send me your email via the app's 'Send Feedback' feature I can add you to TestFlight and you can try the fix there.

**Comment by hussainaloum** [comment]
Thank you for the quick response.
I sent you an email through the app's 'Send Feedback' feature

**Comment by dinesharjani** [comment]
Marking as closed.
