### ISSUE TITLE
DFU progress indicates 100.00% when at 1% upload

### ISSUE THREAD

**Issue by mfikes** [NordicSemiconductor/IOS-nRF-Connect#127]
When uploading, at the 1% progress point, the app indicates 100.00%:

![IMG_FA7793326727-1](https://user-images.githubusercontent.com/1723464/229374815-32863cf0-31ad-43ae-9a43-327f77f0016a.jpeg)

Here is a subsequent image showing it properly displays 2.00% at the 2% point:

![IMG_67566B1F2F0C-1](https://user-images.githubusercontent.com/1723464/229374839-0b4c07d1-bc03-43f2-8f02-f6ca46ef6fc4.jpeg)

**Comment by dinesharjani** [comment]
Fixed. Will be in the next version. Thanks!

**Comment by dinesharjani** [comment]
Will ship in version 2.6.4.
