### ISSUE TITLE
URL in Eddystone format not shown correctly

### ISSUE THREAD

**Issue by ladivin** [NordicSemiconductor/IOS-nRF-Connect#129]
There's a tiny bug in displaying Eddystone data. The URL is missing the "." sign in front of the domain. Instead of `www.zephyrproject.org` the application shows `www.zephyrprojectorg`. Please refer to the attached screenshot. 

Source of Eddystone data: Eddystone sample from Zephyr v3.3.0. 
iOS version: 16.4.1
nRF Connect version: 2.6.3

![EddystoneURL](https://user-images.githubusercontent.com/126091428/233086839-363d3e6d-35d5-4949-9be1-df8a8b2ea325.png)

**Comment by dinesharjani** [comment]
I hear you. I need to check a couple of things and come back to you. Thanks for bringing this up.

**Comment by dinesharjani** [comment]
You are correct. I wanted to check the hex parsing code properly instead of looking at the internal code mapping. But yes, it was a pretty simple bug. Thanks for pointing this out.

Will ship in version 2.6.4.

**Comment by ladivin** [comment]
Thank you for taking care of this!

**Comment by dinesharjani** [comment]
If only everything else was this easy to fix! :)
