### ISSUE TITLE
Advertising Custom UUID not supported

### ISSUE THREAD

**Issue by zhamaliddin-kalzhan** [NordicSemiconductor/IOS-nRF-Connect#132]
There is a feature that allows you to advertise custom UUID on the Android version, but I couldn't find it on the iOS version.
Will it be added in the close future?

**Comment by dinesharjani** [comment]
Hi @zhamaliddin-kalzhan this is a planned feature for version 2.7, which I'm working on at the moment. I plan to re-do the Peripheral Tab and custom advertisement UUIDs are a part of it !
