### ISSUE TITLE
BLE - Device information menu

### ISSUE THREAD

**Issue by mpiffari** [NordicSemiconductor/IOS-nRF-Connect#133]
Hi folks,
I'm here to ask information about these two menu asreas:
- Android "Device Information"
- iOS - "System Information"

In particular I'm interested about info of BLE: which APIs are used both for Android and iOS in order to retrieve BLE information?

Android
![1689926291288](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/28917444/deb4922c-8528-4842-9bfc-eb0457d31177)

iOS
![IMG_55B04FFDFDC2-1](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/28917444/75e0c856-0c69-4c6f-a576-d3559bac4f47)

**Comment by dinesharjani** [comment]
Hi @mpiffari ,

On iOS, there's very limited information of the BLE hardware & capabilities. At least when using Public APIs. If you know of any way to gather more information, I'd be very happy to learn about them. We wanted to expand this a lot more, and on the Mac (we haven't released this yet, but we're working on it as much as we can) we were able to add some more information. Presumably we could add even more, but there's a limit to how much time we can dedicate to one thing ;)

Here's a screenshot for you (M1 16" MacBook Pro):
<img width="1063" alt="Screenshot 2023-07-21 at 09 50 01" src="https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/1042411/0351953e-c439-4952-b792-e4aa7e027d34">

**Comment by dinesharjani** [comment]
@mpiffari we don't share nRF Connect code, that's the one app, for now, we're not open-sourcing.

But getting this is quite trivial:

`CBCentralManager.supports(CBCentralManager.Feature.extendedScanAndConnect)`

**Comment by mpiffari** [comment]
@dinesharjani thank for reference.
And for Android: I guess it is all well defined in Android Developers guide, but I can not find correct reference for API that return such capabilities.

**Comment by dinesharjani** [comment]
I leave the Android side to @philips77 He'll reply when he can

**Comment by philips77** [comment]
You have a lot of those methods in `BluetoothAdapter` class here: https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#isLe2MPhySupported()
Some other properties depend on Android version, e.g. native HID support.
