### ISSUE TITLE
For iphone user we have select data parser to signed int or unsigned there is no float for temperature & humidity

### ISSUE THREAD

**Issue by Mittul98** [NordicSemiconductor/IOS-nRF-Connect#139]
![image](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/113215495/fe3bbaab-71ec-48ea-ae12-01f3d072c71d)
![image](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/113215495/15cbb4f9-5c96-48d2-9723-ba6e0b50175d)

**Comment by dinesharjani** [comment]
Noted. Thanks for your feedback. I'll try to work on this today.

**Comment by dinesharjani** [comment]
@Mittul98 can you provide sample firmware to test this out?

**Comment by xingguo-huang2** [comment]
Similar situation here. Needs to fix this bug. It's been going on for at least 3 weeks.

**Comment by dinesharjani** [comment]
@xingguo-huang2 do you have a sample firmware that produces the Data in the formats you'd like me to add parsers for?
