### ISSUE TITLE
Crashing on iOS 11.1 when during scan 

### ISSUE THREAD

**Issue by Moreiq** [NordicSemiconductor/IOS-nRF-Connect#14]
App is crashing when scanning for Eddystone beacons

**Comment by jovirus** [comment]
@Moreiq  Thank you for reporting this, I have made an update version, if you wish to make a test, you can send me your appleID to mag@nordicsemi dot no

**Comment by Moreiq** [comment]
Appreciate! Please note its lunoff@me.com

Regards,

Boris

**Comment by jovirus** [comment]
@Moreiq you have been invited. Please download the app on TestFlight.

**Comment by Moreiq** [comment]
Thanks for invite but missing redeem code.

Rgrds/Boris

**Comment by jovirus** [comment]
I have re send you an invitation.

**Comment by Moreiq** [comment]
Hi,

Well received. Issue solved!

Many thanks!

Boris

**Comment by OZ1** [comment]
When this fix would be uploaded to AppStore?
