### ISSUE TITLE
Unable to send notifications

### ISSUE THREAD

**Issue by philips77** [NordicSemiconductor/IOS-nRF-Connect#141]
Steps to reproduce:
1. Create an Advertiser and add Heart Rate service
2. Set up GATT server with Heart Rate Service and add Heart Rate Measurement characteristic with Read and Notify properties and Read permission.
3. Enable both.
4. Connect to the iPhone from another phone, I'm using nRF Connect for Android.
5. On the other phone enable notifications for HRM characteristic.
6. Observe, that nRF Connect for iOS shows up a connection pane.
7. **Issue 1**: observe, that the discovered device name is truncated. I see "ixel 7" or "ixel 7E" instead of "Pixel 7".
8. The connection states goes to *Connecting*. Sometimes it doesn't change to *Connected*. In that case **Issue 2**: sending a notification by clicking the arrow doesn't work. Nothing happens.
10. **Issue 3**: there only arrow allows to send notification(?), but there's no way to set a value for reading. 
11. **Issue 4**: If state changes to *Connected*, the Client tab shows no services. Only "This device does not advertise any services". GATT services of the connected device is not visible.

I tried to repeat the same and encountered more issues:
1. When I reconnect from nRF Connect for Android the Advertiser and Server turn off.
2. Sometimes, even after disconnecting from Android, the connection state is still *Connecting* and the pane doesn't show up until I refresh Scanner tab.
3. In logs I see a lot of "Connected." messages, but no "Disconnected.".

![Screenshot 2023-12-21 at 15 24 58](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/6576580/92275edd-5e7d-47db-b95a-a0936ed25b47)
Setup

![Screenshot 2023-12-21 at 15 24 46](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/6576580/3ad36e9d-6cd5-43f8-b933-2986ea84eaf2)
Connecting state with "ixel 7E"

![Screenshot 2023-12-21 at 15 25 41](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/6576580/45e17338-7c10-4c70-bc44-c612253a8025)
Not working button to send notifications

![Screenshot 2023-12-21 at 15 42 19](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/6576580/e20fa783-0de0-4979-8890-d0ad82364513)
Empty services

![Screenshot 2023-12-21 at 15 44 19](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/6576580/3fdd83f4-f3e6-4230-bdea-b432efa3d7cd)
Logs

**Comment by xingguo-huang2** [comment]
I am having a similar situation. nRF needs to fix this bug asap. It worked fine before the new version. Right now, it is just a useless app on my iPhone.
