### ISSUE TITLE
Export of log does not work anymore since build 51

### ISSUE THREAD

**Issue by sensoryx** [NordicSemiconductor/IOS-nRF-Connect#142]
The following procedure used to work until before build 51 and now fails at the last step:

1) Connect to peripheral
2) Activate notifications on one characteristic
3) Click on the "log" tab
4) Select "Text" or CSV
5) Click on "Share"

When trying to share a data log, nothing happens.

**Comment by dinesharjani** [comment]
Hmm, this is either something stupid or it's related to calling the Apple framework to show the 'Share' sheet. Regardless, I'll have a look. Thanks again!

**Comment by dinesharjani** [comment]
Yeah, this one was something stupid. A fix will ship in version 2.7.3. Thanks for your help!
