### ISSUE TITLE
Notification symbol does not always turn blue

### ISSUE THREAD

**Issue by sensoryx** [NordicSemiconductor/IOS-nRF-Connect#143]
When connecting to a peripheral and then clicking on the down-arrow to enable notifications, sometimes, the arrow does not turn blue, but notifications work. Sometimes, the arrow of another characteristic turns blue instead.

**Comment by dinesharjani** [comment]
Yup, I've seen this myself. You're correct. I was planning on tackling this for the Client / Server screen rewrite, but I'll have a look when I can to fix the current screen. Thanks for keeping us honest!
