### ISSUE TITLE
iOS log copy no longer works

### ISSUE THREAD

**Issue by bensmith83** [NordicSemiconductor/IOS-nRF-Connect#144]
It seems that with the addition of the line copy function on the log tab that not the Copy and Share buttons at the top no longer work. I tap copy but nothing appears on the clipboard. Individual line copy does work.

**Comment by dinesharjani** [comment]
Yup, I fixed this just yesterday and will ship as part of 2.7.3. Thank you for reporting it.

**Comment by bensmith83** [comment]
Amazing. Thank you.
