### ISSUE TITLE
iOS App crashes on "start" press for DFU

### ISSUE THREAD

**Issue by alexheslop** [NordicSemiconductor/IOS-nRF-Connect#146]
I'm connecting to an nRF52832 chip using the iOS nRF Connect app, and trying to trigger a DFU. When I load the file and press start to kick off the transfer, the application crashes and resets. This is with an iPhone X on iOS 16.7.4.

**Comment by reddwarfSiddis** [comment]
Same with nRF5340. Worked great in last release

**Comment by dinesharjani** [comment]
@reddwarfSiddis So for the n5340, I believe it's a crash we tried to fix, but didn't fix, and I did not merge it properly for the newest release. But we have a fix for it. I'm trying to add some more fixes related to iPad use of the app and hopefully I can send it to Apple for release this week. Sorry for the inconvenience.

**Comment by dinesharjani** [comment]
Ok, the nRF5340 should be fixed in 2.7.5, which is in the App Store already.
@alexheslop - what SDK version is the DFU? I presume this is 'NordicDFU' and not the newer Zephyr / McuMgr, correct?

**Comment by philips77** [comment]
Could you paste here the *manifest.json* file from the ZIP which you're trying to upload?

**Comment by alexheslop** [comment]
{
    "format-version": 0,
    "time": 1706197950,
    "files": [
        {
            "load_address": 49664,
            "version_MCUBOOT": "0.0.0+0",
            "type": "application",
            "board": "development_kit",
            "soc": "nRF52832_QFAA",
            "size": 229664,
            "file": "app_update.bin",
            "modtime": 1706197950
        }
    ],
    "name": "************************************",
    "firmware": {
        "zephyr": {
            "revision": "91eb13d3afd7ddc7dacfb7435a93838392bd714b-dirty"
        },
        "nrf": {
            "revision": "75adfe8909fbac1c2e0ede465448d1ce2821dfa9-dirty"
        }
    }
}

**Comment by dinesharjani** [comment]
Let me try this out tomorrow. I think I see a possible issue when parsing the manifest that I might need to fix. Thanks.

**Comment by alexheslop** [comment]
Thanks @dinesharjani!

**Comment by dinesharjani** [comment]
@alexheslop something weird is going on during Unzip. It's not doing what I expect. I imagine when you select the file, the Preview is not populated?

**Comment by alexheslop** [comment]
![IMG_3698](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/39192152/7951619b-cf14-47aa-b131-eff4d91802e5)
![IMG_3699](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/39192152/d3a773f9-7257-45d4-81b7-6d340c10936b)

**Comment by alexheslop** [comment]
It seems to preview it okay @dinesharjani, but it fails instantly on sending the request

**Comment by dinesharjani** [comment]
Okay. But it doesn't crash.

You can swipe left to the Logs, enable all Levels, and get more info about what happened.
