### ISSUE TITLE
Modal Screen already visible - Alert prevents opening connected device 

### ISSUE THREAD

**Issue by logsol** [NordicSemiconductor/IOS-nRF-Connect#149]
I am able to scan for devices but when I connect to my peripheral, I cannot go to the services and characteristics. I see this alert view, that says: 

"Panel already open - There is already a Modal Screen visible to the user"

<img width="246" alt="Screenshot 2024-02-26 at 17 31 44" src="https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/692826/59f73c93-62f1-4a4a-ac0c-492426dbaefd">

This did not happen before on my iPhone SE 2nd generation, but keeps happening on my iPhone 15. 

Any hints?

**Comment by dinesharjani** [comment]
Easiest way to fix this is to go to Settings -> Version Number and tap it about 15 times until "Developer Mode" is enabled. When it is, scroll back up and do "Restart App". Should fix it.

And then, if you can next tell me a sequence of steps to follow to reproduce this on an iPhone 15, I can fix it.

Thanks.

**Comment by dinesharjani** [comment]
I will have another look at the code tomorrow as well to see if I can get a glimpse of how this could happen. The iPhone 14/15s unfortunately have a couple of weird situations that prior iPhone(s) don't get into, I presume because of the Dynamic Island. Was this on a Max? Plus? Pro? Or regular iPhone 15?

**Comment by logsol** [comment]
Oh wow thanks for the quick reply with the workaround. I’ll be sure to check this tomorrow. Unfortunately I don’t have any repro steps other than what I already wrote. However I’ll keep an eye out if it happens again and if there’s some pattern. I am using a regular iPhone 15.

**Comment by dinesharjani** [comment]
Yeah, I don't have a 15. But already there have been a couple of issues with 14/15 so 16 is on my list now, though that's a few months away. The Simulator helps, but it doesn't work with Bluetooth so I have to mock the Data. Anyway - let me know tomorrow if this works for you. And if there's a sequence of steps to reproduce this, please let me know.

Version 2.7.6 was also just submitted to Apple. It has a lot of changes, I don't remember now if this kind of state management is involved or not, so I'm not expecting this to fix it.

**Comment by dinesharjani** [comment]
Okay, I think I know the cause. It's something to do with rotation - device on landscape, with a device open. Switch tab to RSSI, go to portrait, back to Scanner and there's the Modal Alert. It's rotation logic at fault.

**Comment by dinesharjani** [comment]
This is fixed and will ship with version 2.7.7.
