### ISSUE TITLE
MacBook Silicon,  Sonoma needs SEGGER universal

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Connect#150]
![image](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/2365961/3d5232c0-7c10-4508-ae3a-d6b37410ae66)

**Comment by DG12** [comment]
Installed Segger Universal 796 now

nRFconnect complains:

```
2024-03-11T00:11:28.994Z INFO Using JLink version: 
JLink_V7.96 

2024-03-11T00:11:28.994Z WARN Installed JLink version 
does not match the expected version (JLink_V7.88j)

```

**Comment by dinesharjani** [comment]
Hi Dennis, we appreciate your feedback. But this GitHub is about the iOS / Mac version(s) of nRF Connect. You're providing feedback about the general nRF Connect for Desktop. I recommend you share your feedback in our [DevZone forums](https://devzone.nordicsemi.com/). Meanwhile, I'll have to mark these issues as closed - sorry for the inconvenience.
