### ISSUE TITLE
WIki change log should refer to release_notes

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Connect#151]
http://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases/release-notes-changelog.html

Should be:
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/releases_and_maturity/release_notes.html

**Comment by dinesharjani** [comment]
Closed since this refers to nRF Connect for Desktop
