### ISSUE TITLE
README typo error. Should be "nRF Connect for Android" instead of "nRF Connect for iOS" 

### ISSUE THREAD

**Issue by Jacky-soft** [NordicSemiconductor/IOS-nRF-Connect#152]
![Screenshot 2024-03-22 at 7 40 39 AM](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/81851380/6a38121a-9686-46fb-b002-349fa0845686)

Please see the screenshot above.
https://github.com/NordicSemiconductor/IOS-nRF-Connect?tab=readme-ov-file#related-projects

**Comment by dinesharjani** [comment]
Fixed. Thank you.
