### ISSUE TITLE
Version question 2.7.6(83) in use. Is 2.7.7 available?

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Connect#153]
App store has 

> nRF connect for mobile The #1 Bluetooth LE utility
> 
> ...
> What's New
> Version 2.7.6   3w ago
> 
TestFlight shows 2.7.6(71)

I have it installed Build Number 83 on my iPhone.

Your email of  3/11/24, 06:44 referenced 2.7.7 .
Is that available?

**Comment by dinesharjani** [comment]
No, not yet. I might make it available via TestFlight today/tomorrow.

**Comment by dinesharjani** [comment]
Note: 2.7.7 might be delayed because it's the target release for an incoming feature that we're working on.
