### ISSUE TITLE
Export CSV needs corrections 2.7.6 (83) - defect

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Connect#154]
1) A CSV file should have 1 or more heading lines
 For example

**2024-03-22,"Puck.js 9efe","nRF Connect","2.7.6(83)"
Time,Status,LogLevel**
18:32:29,Connected Device,verbose,Attempting to connect...
18:32:29,Connected Device,debug,cbCentralManager.connect()
18:32:32,Connected Device,debug,[Callback] centralManager(central, didConnect: peripheral)
18:32:32,Connected Device,normal,Connected.

2) Time should include milliseconds. For example:
**18:32:29.039,
18:32:29.503,**

3) Filename should be less cryptic and have correct extension.
IS: 
text-754249830F21-1.txt
Suggestion:
**Puck.js_9e9f_240321.1832.csv**   (spaces replaced with underscore)

4) Messages with embedded commas create an additional column. This can be prevented by enclosing the message in quotes. See attached screen shot.

5) I don't understand what second column "Connected Device" means?
6) "Export as text" needs timestamps.

Thank you for your consideration.

![image](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/2365961/1e3a261c-1f85-4274-be13-52f3fd4aab7b)

Complete log for this connection attempt(exported as csv):
++++++++++++++++++++++++++++++++++++++++++++++++++
18:32:29,Connected Device,verbose,Attempting to connect...
18:32:29,Connected Device,debug,cbCentralManager.connect()
18:32:32,Connected Device,debug,[Callback] centralManager(central, didConnect: peripheral)
18:32:32,Connected Device,normal,Connected.
18:32:32,Connected Device,verbose,Discovering Services...
18:32:32,Connected Device,debug,peripheral.discoverServices(nil)
18:32:32,Connected Device,debug,[Callback] peripheral(peripheral, didDiscoverServices: nil)
18:32:32,Connected Device,normal,Discovered Nordic UART Service Services.
18:32:32,Connected Device,verbose,Discovering Characteristics for Nordic UART Service...
18:32:32,Connected Device,debug,peripheral.discoverCharacteristics(nil, for: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E)
18:32:32,Connected Device,debug,[Callback] peripheral(peripheral, didDiscoverCharacteristicsFor: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E, error: nil)
18:32:32,Connected Device,verbose,Discovering Descriptors for Characteristic UART TX Characteristic...
18:32:32,Connected Device,debug,peripheral.discoverDescriptors(for: 6E400003-B5A3-F393-E0A9-E50E24DCCA9E)
18:32:32,Connected Device,verbose,Discovering Descriptors for Characteristic UART RX Characteristic...
18:32:32,Connected Device,debug,peripheral.discoverDescriptors(for: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E)
18:32:32,Connected Device,debug,[Callback] peripheral(peripheral, didDiscoverDescriptorsFor: 6E400003-B5A3-F393-E0A9-E50E24DCCA9E, error: nil)
18:32:32,Connected Device,normal,Discovered Characteristics UART TX Characteristic and UART RX Characteristic for Service Nordic UART Service.
18:32:32,Connected Device,debug,[Callback] peripheral(peripheral, didDiscoverDescriptorsFor: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E, error nil)
18:32:32,Connected Device,normal,Discovered Client Characteristic Configuration for Characteristic UART TX Characteristic
18:32:32,Connected Device,normal,Characteristic UART RX Characteristic has no Descriptors.
18:32:37,Connected Device,debug,[Callback] centralManager(central, didDisconnectPeripheral: peripheral, error: The connection has timed out +unexpectedly.)
18:32:37,Connected Device,normal,Disconnected.

**Comment by dinesharjani** [comment]
@DG12 I made changes, and submitted 2.7.7 to TestFlight. Should be out tomorrow at the latest. Feel free to re-open this issue with further changes / improvements you'd like to see. Thanks for your input.
