### ISSUE TITLE
filename for Export CSV should have  .CSV extension - improvement

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Connect#157]
A better name would be 
"Ruuvi_450A_240402.1756_nRFconnect.**csv**"
(where "Scan Response" is used as the prefix with spaces being substituted with underscores.

![image](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/2365961/89f749c4-7482-47e1-ab35-14fc54a5d861)

Thank you

**Comment by dinesharjani** [comment]
Ok, I'm doing "Device Name".[txt/csv]. This should be better. Going to mark this as closed, and send an update via TestFlight.
