### ISSUE TITLE
Uploading an image that uses external SPI flash throws “Error: Not Supported”

### ISSUE THREAD

**Issue by zpm1066** [NordicSemiconductor/IOS-nRF-Connect#159]
Hello,
I’m seeing a potential bug when uploading an image to the external flash of a device.

After the upload, I get the “Error: Not supported” and device disconnects. However, FOTA BLE image upload works fine.

Uploading an image that uses the SoC flash is fine. After the upload, nRF Connect waits for device to swap partitions and reboot with the new image, and messages states “Success!”.

Please review and provide a bug fix.

nRF Connect is a great app. Keep it up! Thank you.

![Screen Shot 2024-04-19 at 12 00 18 PM](https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/43045762/d0559416-5e55-4f21-9435-92341543a1b8)

<img width="352" alt="Screen Shot 2024-04-19 at 12 16 05 PM" src="https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/43045762/c0d17eed-34f4-492c-a1a0-c9e12af47469">

<img width="343" alt="Screen Shot 2024-04-19 at 12 13 10 PM" src="https://github.com/NordicSemiconductor/IOS-nRF-Connect/assets/43045762/3de2b2dd-1776-4bb3-9f9b-609572760441">

**Comment by philips77** [comment]
I think this applies to "Erase app storage" command. It doens't matter for the success of upgrading the device. 
You may also disable erasing storage.

**Comment by philips77** [comment]
Which upload mode are you using? Are you using Direct XIP as well?

**Comment by zpm1066** [comment]
I’m using “DFU” from nRF Connect for mobile iOS and using the defaults.
