### ISSUE TITLE
Make DFU rename optional

### ISSUE THREAD

**Issue by ambrice** [NordicSemiconductor/IOS-nRF-Connect#16]
Recent nRF Connect update made it so I can not do a DFU update to my device because of bugs in the SDK's rename functionality.  Can you make this an option?  Details:

https://devzone.nordicsemi.com/question/179272/nrf-connect-ios-dfu-fails-for-unbonded-buttonless-dfu-service/

**Comment by philips77** [comment]
Hi, I answered in a comment on the link you provided. It's a matter of DFU library rather then nRF Connect, as this functionality is built in into the library. We do not plan to have the renaming feature optional, as it ensures that the iPhone will connect to the right device during the DFU process. Please, fix the issue on your side, or return Invalid opcode when 0x02 request is sent, as it used to be in SDK 12 and 13.

**Comment by ambrice** [comment]
I can fix the issue on my side, but I can't update the device with the fix.  So to summarize:

1. We wrote our buttonless DFU application per the (incorrect) documentation
2. We tested it on Android and iPhone, working fine.
3. We shipped it to the customer, did several updates successfully using nRF Connect
4. After latest nRF Connect update, customer can no longer use it to update device, due to a bug in the SDK where an async SVC call is made without checking if it's initialized first, causing a hard fault.
5. I can update the app with a fix, and fix the SDK, but I have to tell the customer to go buy an Android phone to be able to update to it.

**Comment by philips77** [comment]
Ok, I get it. Do you use nRF Connect to update the devices, or have your own app, where you could use the updated DFU Library with option to disable this feature?

**Comment by ambrice** [comment]
We are using nRF Connect.

**Comment by jovirus** [comment]
@ambrice 
We can make a setting menu for DFU, so you can choose to disable the renaming function.
I hope that will work.

**Comment by jovirus** [comment]
@ambrice I would like to invite you for testing the new feature when using DFU, which gives you option to switch off the renaming function. If you have appleid, I add you into our Testflight program.

**Comment by ambrice** [comment]
@jovirus It's apple.developer@datasoft.com.  Thanks!

**Comment by jovirus** [comment]
@ambrice You are now invited on Testflight.

**Comment by ambrice** [comment]
Tested it and working well, thanks.
