### ISSUE TITLE
BF 720 Device integration in Swift

### ISSUE THREAD

**Issue by jatin141141** [NordicSemiconductor/IOS-nRF-Connect#161]
I have one issue: I want to retrieve the data in beurer BF 720, but how do I obtain the PIN when the device is connected via Bluetooth?

**Comment by dinesharjani** [comment]
I'm sorry to say this is not an nRF Connect issue. If you try to read an attribute that requires encryption, it triggers pairing request from iOS.

**Comment by jatin141141** [comment]
Thanks @dinesharjani but how we can resolve this issue in our application we have try all the way can you please provide any link to connect successfully beurer BF 720. please help me

Thanks in Advance
