### ISSUE TITLE
Accessory setup kit

### ISSUE THREAD

**Issue by mpiffari** [NordicSemiconductor/IOS-nRF-Connect#166]
Hi @dinesharjani ,
Actually, NRF Connect iOS, support AccessorySetupKit?

[Apple Docs ref](https://developer.apple.com/documentation/AccessorySetupKit)

**Comment by philips77** [comment]
Hello,
nRF Connect is a generic app, which allows to scan and connect to any Bluetooth LE device.
Accessory Setup Kit is made for apps tailored to be used with specified devices. It needs to know the service UUID beforhand and registers a name and an icon. It's a different use case.
