### ISSUE TITLE
Can't Select Third Item Under "My Firmwares"

### ISSUE THREAD

**Issue by GoodnatureBeacon** [NordicSemiconductor/IOS-nRF-Connect#21]
I have been unable to select the third item in the list "My Firmwares", if I move the same package to number 2 by deleting the one above it it works fine. Or if it is higher than number 3 in the list it works. Only the third item doesn't work.

**Comment by mostafaberg** [comment]
@GoodnatureBeacon Thanks for reporting this, you have a very similar report #20 so I'll close this one as it's a duplicate, see the solution there for now and we will have a fix out as soon as possible!, sorry for any inconvenience caused!
