### ISSUE TITLE
Unable to complete connection on iPhone 8

### ISSUE THREAD

**Issue by sskcorea** [NordicSemiconductor/IOS-nRF-Connect#24]
Hi

I've tried to make a connection between Ubuntu Bluez 5.42 and nRF Connect on iPhone 8.

In Bluez side, it looks like connection was made successfully. 
If I issue "hcitool con" command it returns with message like below:
Connections:
        > LE 4F:35:8F:8D:DB:21 handle 128 state 1 lm SLAVE
And even I can read "Manufacturer Name String" attribute from bluetoothctl tool.

However in nRF side, the circular progress bar does not stop and it does not show anything on the screen.

If you tell me how to get logs, I will post it.

Thanks

**Comment by jovirus** [comment]
Hi, it seems the nRF Connect did not connect to Ubuntu Bluez, it stays in connection status. Does Bluez setup as a Gatt Server?

**Comment by mostafaberg** [comment]
Probably because you need to pair ? have you successfully paired?

**Comment by sskcorea** [comment]
FYI. the problem has been solved since iOS 11.3
