### ISSUE TITLE
RSSI chart straight line

### ISSUE THREAD

**Issue by MaartenMeta** [NordicSemiconductor/IOS-nRF-Connect#29]
When I discover BLE devices the RSSI chart shows sometimes a straight line and after a while starts bending.
I assume that this is because the iOS device does not detect the BLE device and keeps the value.
This should just be like with the Android device that the line stops when it does not receive a packet within a x period of time.

**Comment by mostafaberg** [comment]
Hi @MaartenMeta , do you have a screenshot of how it looks like on both sides so we can have some visual reference when we fix this issue ? thanks a lot for your help and sorry for any inconvenience! :)

**Comment by MaartenMeta** [comment]
See pictures below: (the android stops sometimes but this is a bug in the phone itself, other android phones do not show this)
IOS
![ios](https://user-images.githubusercontent.com/12763109/38863443-effd0d56-4237-11e8-8a30-58dc2afaae7d.png)
ANDROID
![android](https://user-images.githubusercontent.com/12763109/38863444-f010f01e-4237-11e8-98d1-6ce4cdd9500e.png)
