### ISSUE TITLE
Clear device cache

### ISSUE THREAD

**Issue by amitchone** [NordicSemiconductor/IOS-nRF-Connect#30]
Hi, 

I'm aware that the Android version of the application allows users to clear cached device information, such as characteristic UUIDs and a whole host of other related things. Is this possible on the iPhone application? 

Thanks,
Adam

**Comment by philips77** [comment]
Hi,
This is not allowed by the iOS API. But iOS deals with the cache correctly (according to the spec). If your device have Service Changed characteristic and it's not bonded, iOS will not cache services. If it's bonded, it will cache, but if will invalidate then on SC indication.
Services on not bonded devices without Service Changed characteristic will be cached. Restart if the Bluetooth or phone clears the cache.
