### ISSUE TITLE
iOS-nRF-Connect Connect iOS source Code

### ISSUE THREAD

**Issue by MMooreGitHub** [NordicSemiconductor/IOS-nRF-Connect#31]
Hi,

Can you please provide the link to the iOS (Swift/Objective-C source code for this app?
I understand this repo is used to track issues.

**Comment by mostafaberg** [comment]
The project isn’t open sourced, if you need examples you may look at our other apps , nRF Toolbox would be the best example.

**Comment by MMooreGitHub** [comment]
Ok, thank you!
