### ISSUE TITLE
Re: Issue#34- nrFConnect/ButtonlessDFU question

### ISSUE THREAD

**Issue by MMooreGitHub** [NordicSemiconductor/IOS-nRF-Connect#35]
Hi,
Can you confirm that the nrFConnect app uses the **experimental Buttonless DFU** feature
if we are running SDK 12.x?

**Comment by jovirus** [comment]
nrfconnect is using [ios-dfu-library](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library), so yes,  the experimental Buttonless DFU is supported.
