### ISSUE TITLE
Need reset capability

### ISSUE THREAD

**Issue by DaleScott** [NordicSemiconductor/IOS-nRF-Connect#36]
May be new with latest iPhone version, but when restarting scan, old sources (turned off) still displayed. And, they seem to mask new source from same device with different name. Have to power off cell phone.

**Comment by jovirus** [comment]
Hi @DaleScott 
You can pull down to refresh the device list.
It will clear all devices.

**Comment by DaleScott** [comment]
Wow! Right there in the manual and I missed it! Thanks.
