### ISSUE TITLE
Cannot access log 

### ISSUE THREAD

**Issue by nickbedbury** [NordicSemiconductor/IOS-nRF-Connect#51]
In the Android `nRF Connect`, there is a `Show log` option once connected to a device.  This does not seem supported in the IOS app.

The nRF Connect - IOS user manual mentions being able to extract logs via iTunes Store, but I haven't seen instructions how that works either.

**Comment by philips77** [comment]
Logs are available in iOS version as well. You have to swipe the services pane to the right, just like on Android version. But hold the finger on the middle of the pane, as left edge will navigate you to Scanner screen again.

**Comment by Nbedbury** [comment]
Got it.  Thanks @philips77

**Comment by sandberg75** [comment]
Not working for me in version 2.1.2, build 76
