### ISSUE TITLE
Poor user scan experience

### ISSUE THREAD

**Issue by klyhthwy** [NordicSemiconductor/IOS-nRF-Connect#52]
I use nRF Connect a lot at work, but I am hoping you could fix the filtering experience. We have a very congested BLE environment at our office. When I scan I get a ton of devices and there is not way on the app to sort them by signal strength as far as I know. When I try to filter by RSSI the slider is difficult to get moving. Instead of moving the slider most of the time it moves the screen view over to the RSSI graph. I attached  screenshot and I have made a short video you can find at the link below.
https://youtu.be/MDg7RdRid-Q
![IMG_2612](https://user-images.githubusercontent.com/12037209/54568098-9f20db80-499b-11e9-9209-976cf7ab6fac.PNG)

**Comment by dinesharjani** [comment]
Hi @klyhthwy - we're very happy that you use nRF Connect for iOS at work.

We're currently performing final testing on a full rewrite of nRF Connect, version 2.0. If you'd like to beta-test it and give us your feedback, please e-mail me at [dinesh.harjani@nordicsemi.no](mailto:dinesh.harjani@nordicsemi.no). We'd love to have your feedback as a hard-core user of the app :)
