### ISSUE TITLE
DFU Update Hangs

### ISSUE THREAD

**Issue by rob-brown** [NordicSemiconductor/IOS-nRF-Connect#55]
Sometimes when uploading both the boot loader and the app firmware the app hangs at the disconnecting step after having uploaded the boot loader. Fortunately the nRF Toolbox app works fine.

**Comment by dinesharjani** [comment]
The old version of nRF Connect (1.8.x) was not being updated with new DFU Library improvements and fixes, this is why the nRF Toolbox app worked fine.

This should now be resolved as nRF Connect 2.x is constantly being updated :)
