### ISSUE TITLE
rearranging beacons is a problem

### ISSUE THREAD

**Issue by DG12** [NordicSemiconductor/IOS-nRF-Connect#6]
After a scan, the display is updated with the most recent data, this is GOOD.

Re arranging the beacons based on their most recent signal strength is bad because,
just as you click on one it may change to a different one.

Thank you

**Comment by jovirus** [comment]
@DG12 see this thread [https://github.com/NordicSemiconductor/IOS-nRF-Connect/issues/5](url)

**Comment by DG12** [comment]
It seems that there is a typo in the link you provided.??
