### ISSUE TITLE
Protected Characteristic prevents connecting if not paired

### ISSUE THREAD

**Issue by jbarmanet** [NordicSemiconductor/IOS-nRF-Connect#60]
My device is made of a nRF52832 chip and has one protected characteristic. 
Naturally, this protected characteristic triggers an iOS pairing request when connecting to the device. So far so good.

In the previous version of nRF Connect (pre-2.0) if you were answering "Cancel" to the pairing request, we could still be connected to the device and read the other non-protected characteristics.

Now with the version 2.0, when connecting to the same device, the behavior is quite different: while iOS still fires the pairing request modal, we can see that nRF Connect disconnects instantly in background. After that, if the device was paired, I can ask again for connection and everything works. But if the device was not paired, if I want to connect again, then iOS asks again for pairing... And so on forever.

At the end, the result is that with this new version of nRF Connect I can no longer connect my device at all without pairing.
Even if this does not represent a real issue in my specific case, this is quite a change.

And I would like to understand what is causing this new behavior: is there a trick in the connection process? How do you know if the device is paired or not? 
I would really appreciate some input here, as I have an issue to know if my device was paired or not, and the solution could rely somewhere in this new behavior that you implemented in nRF Connect 2.0. 

Thanks for your help!

**Comment by dinesharjani** [comment]
This should be fixed by now. I remember this being an issue and us updating the app.

If it keeps happening, please re-open the issue or create a new one.
