### ISSUE TITLE
Add ability to sort scan results

### ISSUE THREAD

**Issue by waelbarakat** [NordicSemiconductor/IOS-nRF-Connect#61]
A missing basic feature from nRF Connect app on iOS is the ability to sort the scan results by RSSI. Sometimes we have to go back to LightBlue just for that functionality.

**Comment by philips77** [comment]
Hi,
You may filter by RSSI, leaving only the closest devices visible. Continuous sorting by RSSI is problematic as it will cause reordering devices. This may lead to unintended connections or in general cause the UI to be not readable and blinking.
On the RSSI tab you may select devices you are interested in and they will be colored on the Scanner tab.

**Comment by dinesharjani** [comment]
This feature was added as part of nRF Connect for iOS 2.3.
