### ISSUE TITLE
Accessing logs on iOS

### ISSUE THREAD

**Issue by goodsireric** [NordicSemiconductor/IOS-nRF-Connect#62]
I saw in issue #51 that you "swipe right" on services table to get logs. For me, that just brings me to the DFU screen. What am I missing? Is this no longer possible in the latest version of the app?

I'm trying to figure out throughput by looking at first and last notification times, which was much more intuitive to do in the Android version of the app.

**Comment by philips77** [comment]
Hello,
The new version doesn't have logs yet. We are working on adding this feature. Sorry for the inconvenience.
Please, read more about the current version here: https://devzone.nordicsemi.com/nordic/nordic-blog/b/blog/posts/announcing-nrf-connect-2-0-for-ios

Thank you for your feedback.
