### ISSUE TITLE
mcumgr DFU support

### ISSUE THREAD

**Issue by nwsetec** [NordicSemiconductor/IOS-nRF-Connect#64]
As a user I would greatly appreciate having DFU support for mcumgr as I develop firmware for Zephry/mynewt.

Thanks!

**Comment by nwsetec** [comment]
Cheers for the reply dinesharjani it would be good to know if it was on the greater road map, there is definitely a want for this at the company I work for. cc @carlescufi

**Comment by philips77** [comment]
Yyes. It's definitely on the roadmap. There's just lots of features we want to add.
