### ISSUE TITLE
Feature request: Enable copy from characteristic fields

### ISSUE THREAD

**Issue by andresovela** [NordicSemiconductor/IOS-nRF-Connect#65]
Hi,

I would like to request a feature so that it is possible to copy the values read from a characteristic. See screenshot for context.
![IMG_0371](https://user-images.githubusercontent.com/8990961/69167124-b862c480-0af4-11ea-927a-198fd6a97367.jpg)

I think it would be nice to be able to copy that long value in order to be able to use it somewhere. At the moment I'm forced to manually type the values (just for debugging purposes).

**Comment by andresovela** [comment]
Any updates on this? :( I would _really_ appreciate this feature.

**Comment by dinesharjani** [comment]
![CopyButton](https://user-images.githubusercontent.com/1042411/89795138-ef17b980-db1f-11ea-8635-41942693dfc1.png)

Implemented. Closing the issue. This will ship in the next release of nRF Connect for iOS.

**Comment by andresovela** [comment]
Nice!
