### ISSUE TITLE
The layout is broken 

### ISSUE THREAD

**Issue by davydgeyl** [NordicSemiconductor/IOS-nRF-Connect#71]
Steps to reproduce:
1. Launch the app  in iOS 10.3.2
2. Connect to any Bluetooth device with services

Observed results:
Layout is broken in Advertisment Data and Services screens, see screen shots.
Labels trim the text.

Expected result:
Normal layout, labels showing text

**Comment by dinesharjani** [comment]
Hi @davydgeyl can you attach the screenshots? Is the issue still happening?
