### ISSUE TITLE
DFU service not recognised

### ISSUE THREAD

**Issue by istvanns** [NordicSemiconductor/IOS-nRF-Connect#72]
![nrfconnect_ios_nodfu_2 3 306](https://user-images.githubusercontent.com/49909462/85707899-ebe97b00-b6e3-11ea-8ddc-9f36f8d561d0.png)

iOS version: 13.5.1
App version: 2.3 build 306
Bootloader SDK version: 16.0.0

DFU works with the Android app version 4.24.1 on Android 10 with the same device, so it must be something with the iOS app.

**Comment by philips77** [comment]
Please, restart Bluetooth in iOS settings and try again. Perhaps some previous services have been cached by the system and restarting Bluetooth will fix this.

**Comment by istvanns** [comment]
Right. Had to restart a few times, but it solved the problem. Also had to turn off alternative advertising name (or something similar). Thanks!
