### ISSUE TITLE
facing connectivity issues for connecting nrf52840 eval board with iOS 13.2 above(installed nrf connect app)

### ISSUE THREAD

**Issue by anupam-vvdn** [NordicSemiconductor/IOS-nRF-Connect#73]
Hi, I am Working on nRF52840 and using nRF52840-DK.
Below is my working environment SDK - nRF5_SDK_16.0.0_98a08e2 ,
IDE - Segger Embedded studio (windows 10 - 64 Bit)
Softdevice - s140_nrf52_7.0.1_softdevice
Base code - ble_app_multirole_lesc_s140_pca10056
also using bootloader of dual bank for OTA
My device is scanning and advertising both simultaneously. 
Advertisement interval is 1 second.

I am facing issue to connect nrf52840 dev kit with IOS 13.2 and above,it is working fine with android mobile.
can you please guide in this.

**Comment by philips77** [comment]
Hello, please use https://devzone.nordicsemi.com/ for this kind of questions, as they are not related to nRF Connect for iOS. Our support team will try to help you there.
