### ISSUE TITLE
Log is empty

### ISSUE THREAD

**Issue by serotta58** [NordicSemiconductor/IOS-nRF-Connect#74]
On version 2.3.1 on an iPad, when I swipe to view the log for a connected device, the log text is empty regardless of what I set the filters to, and the plaintext / CSV format option.  Pressing the Share button flashes the possible sharing options, but then closes right away, presumably because there is nothing in the log.

**Comment by dinesharjani** [comment]
Thank you @serotta58 - we're making changes to the app so this can't happen.

This should be fixed in the next release. We're currently not planning any bug-fix releases in the 2.3.x line, so this might take a bit.

**Comment by dinesharjani** [comment]
This is fixed and will ship in the next version of nRF Connect.
