### ISSUE TITLE
Advertising Interval of RSSI in 'Log'

### ISSUE THREAD

**Issue by threekami** [NordicSemiconductor/IOS-nRF-Connect#87]
Hi,

I set my beacon's advertising interval to be 500ms, while in the log the interval of receiving RSSI is floating randomly. Sometimes 1000ms and sometimes 1500ms. Can the interval between each receiving RSSI remain at 500ms, which is the same as the one I set on my beacon?

Cheers,

Asher

**Comment by dinesharjani** [comment]
Advertising Interval calculation is tricky, and it also depends on when the application itself receives the "advertising" events. Which might be cached by the device, the API, the radio, etc.
